### ISSUE TITLE
[BUG] Parse error: expected commit_type

### ISSUE THREAD

**Issue by oradwell** [cocogitto/cocogitto-action#23]
In the latest version of the action in "main" branch, we started getting a parse error. Even though the commits comply to the conventional commit standards

```
Checking all commits
No errored commits

Error: Parse error

Caused by:
     --> 1:1
      |
    1 | 
      | ^---
      |
      = expected commit_type
```

#### To Reproduce

- Create a commit that comply to the conventional commit standards
- Ensure the action is run with no parameters (all default values)

```yaml
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cocogitto/cocogitto-action@main
```

#### Expected behavior

Action should pass the checks with no errors.

#### Additional context

It seems to have been caused by #10
