### ISSUE TITLE
[BUG] Action is checking entire git history instead of only PR commits

### ISSUE THREAD

**Issue by jorgegonzalez** [cocogitto/cocogitto-action#33]
**Describe the bug**

I am trying to use this action to enforce conventional commits in Pull Requests, but it seems to check the entire git history every time? I'm not sure the point of passing in the ref if it isn't going to only check the commits in the pull request.

```
on: [pull_request]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
```

**To Reproduce**

Use config above.

**Expected behavior**

Using the config above, I expect the action to only check against the commits in the current PR.

**Additional context**
